package harlan.sound;

import java.util.HashMap;
import java.util.Map;

public class MusicNames {
	public static Map<Integer, String> musicIds;

	public static void initMusicMap() {
		musicIds = new HashMap<Integer, String>();
		musicIds.put(177,"Adventure");
		musicIds.put(401,"The Adventurer");
		musicIds.put(50,"Al Kharid");
		musicIds.put(102,"Alone");
		musicIds.put(90,"Ambient Jungle");
		musicIds.put(456,"Animal Apogee");
		musicIds.put(36,"Arabian");
		musicIds.put(123,"Arabian2");
		musicIds.put(160,"Army of Darkness");
		musicIds.put(186,"Arrival");
		musicIds.put(571,"The Art of Hocus-Pocus");
		musicIds.put(247,"Artistry");
		musicIds.put(604,"Assault and Battery");
		musicIds.put(816,"Astea Frostweb");
		musicIds.put(24,"Attack1");
		musicIds.put(25,"Attack2");
		musicIds.put(27,"Attack4");
		musicIds.put(180,"Attention");
		musicIds.put(2,"Autumn Voyage");
		musicIds.put(248,"Aztec");
		musicIds.put(152,"Ballad of Enchantment");
		musicIds.put(263,"Bandit Camp");
		musicIds.put(141,"Barbarianism");
		musicIds.put(99,"Baroque");
		musicIds.put(100,"Beyond");
		musicIds.put(83,"Big Chords");
		musicIds.put(474,"Bish Bash Bosh");
		musicIds.put(502,"Bittersweet Bunny");
		musicIds.put(903,"Black Zabeth");
		musicIds.put(154,"Bone Dance");
		musicIds.put(64,"Book of Spells");
		musicIds.put(291,"Borderland");
		musicIds.put(803,"Born To Do This");
		musicIds.put(444,"Bounty Hunter Level 1");
		musicIds.put(443,"Bounty Hunter Level 2");
		musicIds.put(445,"Bounty Hunter Level 3");
		musicIds.put(194,"Brimstail's Scales");
		musicIds.put(785,"Bulwark Beast");
		musicIds.put(104,"Camelot");
		musicIds.put(314,"Castle Wars");
		musicIds.put(325,"Cave Background");
		musicIds.put(389,"Cave of the Goblins");
		musicIds.put(595,"Cavernous Mythology");
		musicIds.put(478,"The Cellar Dwellers");
		musicIds.put(330,"Cellar Song");
		musicIds.put(63,"Chain of Command");
		musicIds.put(487,"Charmin' Farmin'");
		musicIds.put(583,"Chef Surprize");
		musicIds.put(425,"The Chosen");
		musicIds.put(562,"Circus");
		musicIds.put(442,"Clan Wars");
		musicIds.put(67,"Close Quarters");
		musicIds.put(669,"Command Centre");
		musicIds.put(269,"Competition");
		musicIds.put(418,"Corporal Punishment");
		musicIds.put(178,"Courage");
		musicIds.put(234,"Creature Cruelty");
		musicIds.put(169,"Crystal Sword");
		musicIds.put(560,"Dance of Death");
		musicIds.put(593,"The Dance of the Snow Queen");
		musicIds.put(336,"Dangerous Road");
		musicIds.put(326,"Dark");
		musicIds.put(731,"Dead and Buried");
		musicIds.put(476,"Dead Can Dance");
		musicIds.put(84,"Dead Quiet");
		musicIds.put(37,"Deep Wildy");
		musicIds.put(79,"The Desert");
		musicIds.put(779,"Desolo I");
		musicIds.put(781,"Desolo II");
		musicIds.put(799,"Desolo III");
		musicIds.put(802,"Desolo IV");
		musicIds.put(794,"Desolo V");
		musicIds.put(780,"Desolo VI");
		musicIds.put(771,"Desolo VII");
		musicIds.put(790,"Desolo VIII");
		musicIds.put(775,"Desolo IX");
		musicIds.put(801,"Desolo X");
		musicIds.put(859,"Destiny");
		musicIds.put(532,"Diango's Little Helpers");
		musicIds.put(782,"Divine Skinweaver");
		musicIds.put(537,"Dogs of War");
		musicIds.put(624,"Don't Panic Zanik");
		musicIds.put(56,"Doorways");
		musicIds.put(361,"Down Below");
		musicIds.put(143,"Down to Earth");
		musicIds.put(358,"Dragontooth Island");
		musicIds.put(327,"Dream");
		musicIds.put(47,"Duel Arena");
		musicIds.put(684,"The Duke");
		musicIds.put(310,"Dwarf Theme");
		musicIds.put(366,"Eagle Peak");
		musicIds.put(273,"Easter Jig");
		musicIds.put(69,"Egypt");
		musicIds.put(148,"Emotion");
		musicIds.put(138,"Emperor");
		musicIds.put(667,"Eruption");
		musicIds.put(17,"Escape");
		musicIds.put(492,"Exam Conditions");
		musicIds.put(106,"Expanse");
		musicIds.put(41,"Expecting");
		musicIds.put(337,"Faithless");
		musicIds.put(72,"Fanfare");
		musicIds.put(166,"Fanfare2");
		musicIds.put(167,"Fanfare3");
		musicIds.put(602,"Fear and Loathing");
		musicIds.put(463,"Fire and Brimstone");
		musicIds.put(119,"Fishing");
		musicIds.put(163,"Flute Salad");
		musicIds.put(558,"Food For Thought");
		musicIds.put(121,"Forbidden");
		musicIds.put(98,"Forever");
		musicIds.put(409,"Frogland");
		musicIds.put(603,"Funny Bunnies");
		musicIds.put(159,"Gaol");
		musicIds.put(125,"Garden");
		musicIds.put(722,"Ghost of Christmas Presents");
		musicIds.put(832,"Glacialis I");
		musicIds.put(834,"Glacialis II");
		musicIds.put(827,"Glacialis III");
		musicIds.put(811,"Glacialis IV");
		musicIds.put(824,"Glacialis V");
		musicIds.put(808,"Glacialis VI");
		musicIds.put(831,"Glacialis VII");
		musicIds.put(810,"Glacialis VIII");
		musicIds.put(833,"Glacialis IX");
		musicIds.put(837,"Glacialis X");
		musicIds.put(817,"Gluttonous Behemoth");
		musicIds.put(22,"Gnome King");
		musicIds.put(33,"Gnome Village");
		musicIds.put(101,"Gnome Village2");
		musicIds.put(112,"Gnomeball");
		musicIds.put(346,"Goblin Game");
		musicIds.put(313,"Goblin Village");
		musicIds.put(116,"Greatness");
		musicIds.put(432,"Grimly Fiendish");
		musicIds.put(246,"Grotto");
		musicIds.put(466,"Ground Scape");
		musicIds.put(128,"Grumpy");
		musicIds.put(507,"Guthix's Hunter");
		musicIds.put(907,"Halloween Party");
		musicIds.put(644,"Hare-brained Machines");
		musicIds.put(76,"Harmony");
		musicIds.put(46,"Harmony2");
		musicIds.put(612,"Head to Head");
		musicIds.put(190,"Heart and Mind");
		musicIds.put(97,"Hermit");
		musicIds.put(55,"High Seas");
		musicIds.put(205,"High Spirits");
		musicIds.put(454,"Home Sweet Home");
		musicIds.put(621,"Homescape");
		musicIds.put(718,"Honkytonky Harmony");
		musicIds.put(716,"Honkytonky Newbie Melody");
		musicIds.put(719,"Honkytonky Sea Shanty");
		musicIds.put(18,"Horizon");
		musicIds.put(477,"Hot 'n' Bothered");
		musicIds.put(717,"I'm Counting on You");
		musicIds.put(87,"Ice Melody");
		musicIds.put(522,"Icy a Worried Gnome");
		musicIds.put(523,"Icy Bones");
		musicIds.put(523,"Icy Trouble Ahead");
		musicIds.put(511,"In the Clink");
		musicIds.put(188,"In the Manor");
		musicIds.put(469,"In the Pits");
		musicIds.put(494,"Incarceration");
		musicIds.put(96,"Inspiration");
		musicIds.put(412,"Into the Abyss");
		musicIds.put(683,"Itsy Bitsy...");
		musicIds.put(6,"Jolly-R");
		musicIds.put(460,"Joy of the Hunt");
		musicIds.put(209,"Jungle Bells");
		musicIds.put(483,"Jungle Community");
		musicIds.put(453,"Jungle Hunt");
		musicIds.put(172,"Jungle Island");
		musicIds.put(208,"Jungle Island XMAS");
		musicIds.put(479,"Jungle Troubles");
		musicIds.put(114,"Jungly1");
		musicIds.put(117,"Jungly3");
		musicIds.put(9,"Kingdom");
		musicIds.put(191,"Knightly");
		musicIds.put(374,"Knightmare");
		musicIds.put(189,"Land of Snow");
		musicIds.put(164,"Landlubber");
		musicIds.put(60,"Lasting");
		musicIds.put(642,"Lazy Wabbit");
		musicIds.put(293,"Legend");
		musicIds.put(66,"Legion");
		musicIds.put(320,"Lighthouse");
		musicIds.put(113,"Lightness");
		musicIds.put(74,"Lightwalk");
		musicIds.put(161,"Long Ago");
		musicIds.put(12,"Long Way Home");
		musicIds.put(309,"Looking Back");
		musicIds.put(407,"The Lost Melody");
		musicIds.put(420,"The Lost Tribe");
		musicIds.put(20,"Lullaby");
		musicIds.put(818,"Luminescent Icefiend");
		musicIds.put(572,"Magic and Mystery");
		musicIds.put(185,"Magic Dance");
		musicIds.put(235,"Magic Magic Magic");
		musicIds.put(184,"Magical Journey");
		musicIds.put(544,"Making Waves");
		musicIds.put(559,"Malady");
		musicIds.put(328,"March");
		musicIds.put(156,"Mausoleum");
		musicIds.put(157,"Medieval");
		musicIds.put(193,"Mellow");
		musicIds.put(317,"Melodrama");
		musicIds.put(365,"Melzar's Maze");
		musicIds.put(552,"The Mentor");
		musicIds.put(600,"Method of Madness");
		musicIds.put(107,"Miles Away");
		musicIds.put(534,"Mind Over Matter");
		musicIds.put(65,"Miracle Dance");
		musicIds.put(668,"Mobilising Armies");
		musicIds.put(200,"The Mollusc Menace");
		musicIds.put(21,"Monarch Waltz");
		musicIds.put(343,"Monster Melee");
		musicIds.put(10,"Moody");
		musicIds.put(48,"Morytania");
		musicIds.put(515,"Mudskipper Melody");
		musicIds.put(236,"Mutant Medley");
		musicIds.put(348,"Narnode's Theme");
		musicIds.put(245,"Natural");
		musicIds.put(316,"The Navigator");
		musicIds.put(155,"Neverland");
		musicIds.put(62,"Newbie Melody");
		musicIds.put(127,"Nightfall");
		musicIds.put(594,"No Way Out");
		musicIds.put(587,"Null and Void");
		musicIds.put(633,"On the Wing");
		musicIds.put(7,"Overture");
		musicIds.put(732,"The Pact");
		musicIds.put(93,"Parade");
		musicIds.put(588,"Pest Control");
		musicIds.put(419,"Pheasant Peasant");
		musicIds.put(819,"Plane-freezer Lakhrahnaz");
		musicIds.put(682,"Poison Dreams");
		musicIds.put(398,"The Power of Tears");
		musicIds.put(202,"Prime Time");
		musicIds.put(149,"Principality");
		musicIds.put(413,"The Quiz Master");
		musicIds.put(318,"Ready For Battle");
		musicIds.put(89,"Reggae2");
		musicIds.put(289,"Rellekka");
		musicIds.put(402,"The Rogues' Den");
		musicIds.put(390,"Romper Chomper");
		musicIds.put(429,"Roots and Flutes");
		musicIds.put(467,"The Route of the Problem");
		musicIds.put(57,"Rune Essence");
		musicIds.put(5,"Sad Meadow");
		musicIds.put(493,"Safety in Numbers");
		musicIds.put(290,"Saga");
		musicIds.put(144,"Scape Cave");
		musicIds.put(207,"Scape Hunter");
		musicIds.put(16,"Scape Main");
		musicIds.put(400,"Scape Original");
		musicIds.put(331,"Scape Sad");
		musicIds.put(547,"Scape Santa");
		musicIds.put(321,"Scape Scared");
		musicIds.put(54,"Scape Soft");
		musicIds.put(457,"Scape Summon");
		musicIds.put(679,"Scape Theme");
		musicIds.put(332,"Scape Wild");
		musicIds.put(352,"Scarab");
		musicIds.put(371,"School's Out");
		musicIds.put(92,"Sea Shanty");
		musicIds.put(210,"Sea Shanty XMAS");
		musicIds.put(35,"Sea Shanty2");
		musicIds.put(951,"Seasonal Sports");
		musicIds.put(110,"Serenade");
		musicIds.put(52,"Serene");
		musicIds.put(170,"The Shadow");
		musicIds.put(286,"Shadowland");
		musicIds.put(122,"Shine");
		musicIds.put(120,"Shining");
		musicIds.put(725,"Silent Knight");
		musicIds.put(724,"Smorgasbord");
		musicIds.put(80,"Soundscape");
		musicIds.put(175,"Spirit");
		musicIds.put(77,"Splendour");
		musicIds.put(333,"Spooky");
		musicIds.put(129,"Spooky Jungle");
		musicIds.put(108,"Starlight");
		musicIds.put(151,"Start");
		musicIds.put(111,"Still Night");
		musicIds.put(267,"Sunburn");
		musicIds.put(140,"Talking Forest");
		musicIds.put(397,"Tears of Guthix");
		musicIds.put(339,"The Terrible Tower");
		musicIds.put(109,"Theme");
		musicIds.put(842,"Thieves' Guild I");
		musicIds.put(242,"Time Out");
		musicIds.put(338,"Tiptoe");
		musicIds.put(525,"Title Fight");
		musicIds.put(820,"To'Kash the Bloodchiller");
		musicIds.put(105,"Tomorrow");
		musicIds.put(133,"The Tower");
		musicIds.put(496,"The Trade Parade");
		musicIds.put(130,"Tree Spirits");
		musicIds.put(601,"Trees aren't your Friends");
		musicIds.put(187,"Tremble");
		musicIds.put(165,"Tribal");
		musicIds.put(162,"Tribal Background");
		musicIds.put(94,"Tribal2");
		musicIds.put(681,"Trick or Treat?");
		musicIds.put(192,"Trinity");
		musicIds.put(183,"Troubled");
		musicIds.put(88,"Twilight");
		musicIds.put(473,"TzHaar!");
		musicIds.put(176,"Undercurrent");
		musicIds.put(70,"Unknown Land");
		musicIds.put(70,"Upcoming");
		musicIds.put(75,"Venture");
		musicIds.put(61,"Village");
		musicIds.put(85,"Vision");
		musicIds.put(32,"Voyage");
		musicIds.put(670,"Waiting for Battle");
		musicIds.put(503,"Waiting for the Hunt");
		musicIds.put(49,"The Waiting Game");
		musicIds.put(49,"Wander");
		musicIds.put(295,"Warrior");
		musicIds.put(82,"Waterfall");
		musicIds.put(449,"Wild Isle");
		musicIds.put(475,"Wild Side");
		musicIds.put(435,"Wilderness");
		musicIds.put(42,"Wilderness2");
		musicIds.put(43,"Wilderness3");
		musicIds.put(8,"Wildwood");
		musicIds.put(14,"Winter Funfare");
		musicIds.put(14,"Witching");
		musicIds.put(34,"Wonder");
		musicIds.put(81,"Wonderous");
		musicIds.put(237,"Work Work Work");
		musicIds.put(15,"Workshop");
		musicIds.put(565,"Wrath and Ruin");
		musicIds.put(145,"Yesteryear");
		musicIds.put(146,"Zealot");
		musicIds.put(392,"Zogre Dance");
	}
}
